/* tslint:disable */
/* eslint-disable */
/**
 * cypress-realworld-app-api
 * This is a sample api server for cypress-realworld-app. You can find out more about     the sample app at [cypress-realworld-app](https://github.com/cypress-io/cypress-realworld-app)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface BankAccount
 */
export interface BankAccount {
    /**
     * 
     * @type {string}
     * @memberof BankAccount
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof BankAccount
     */
    uuid?: string;
    /**
     * 
     * @type {string}
     * @memberof BankAccount
     */
    userId?: string;
    /**
     * 
     * @type {string}
     * @memberof BankAccount
     */
    bankName: string;
    /**
     * 
     * @type {string}
     * @memberof BankAccount
     */
    accountNumber: string;
    /**
     * 
     * @type {string}
     * @memberof BankAccount
     */
    routingNumber: string;
    /**
     * 
     * @type {boolean}
     * @memberof BankAccount
     */
    isDeleted?: boolean;
    /**
     * 
     * @type {string}
     * @memberof BankAccount
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof BankAccount
     */
    modifiedAt?: string;
}


