/* tslint:disable */
/* eslint-disable */
/**
 * cypress-realworld-app-api
 * This is a sample api server for cypress-realworld-app. You can find out more about     the sample app at [cypress-realworld-app](https://github.com/cypress-io/cypress-realworld-app)
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface InlineObject
 */
export interface InlineObject {
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    routingNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    bankName?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    accountNumber?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    userId?: string;
}


